# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - xarm_controller
    - scaled_joint_trajectory_controller
    - joint_trajectory_controller



  xarm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm1
      - arm2
      - arm3
      - arm4
      - arm5

  scaled_joint_trajectory_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: false
    joints:
      - arm1
      - arm2
      - arm3
      - arm4
      - arm5

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: false
    joints:
      - arm1
      - arm2
      - arm3
      - arm4
      - arm5
